### PR TITLE
Fixed vavvav-hb yodyod-hb (added anchors)

### PR DESCRIPTION
**Pull request by emmamarichal**
@OdedEzer @markhdavid

Fixed!
See this comment: https://github.com/OdedEzer/heebo/pull/33#issuecomment-1804254632

### CODE REVIEW

**Comment by markhdavid** [comment]
> @OdedEzer @markhdavid
> 
> 
> 
> Fixed!
> 
> See this comment: https://github.com/OdedEzer/heebo/pull/33#issuecomment-1804254632

I'm checking it out. Thank you @emmamarichal Thanks @OdedEzer as well. Can you please allow me a little time (2 days?) before "shipping"? Thanks!

**Comment by markhdavid** [comment]
Hi, please allow a little more time. The vavvav-hb and yodyod-hb `bottom` anchors are off but not being used. There's apparently some strange bug in Glyphs app, under discussion in this forum https://forum.glyphsapp.com/t/yiddish-ligatures-should-not-be-considered-ligatures/25468/8 and in email with their support.

**Comment by markhdavid** [comment]
> > @OdedEzer @markhdavid
> > Fixed!
> > See this comment: [#33 (comment)](https://github.com/OdedEzer/heebo/pull/33#issuecomment-1804254632)
> 
> I'm checking it out. Thank you @emmamarichal Thanks @OdedEzer as well. Can you please allow me a little time (2 days?) before "shipping"? Thanks!

Hi, I sent @emmamarichal a new, improved version of Heebo.glyphs source file. It's necessary in Glyphs App to manually set glyph properties Category / Subcategory to Letter / Other in the selection window for each of the two digraph characters that take bottom anchors (vavvav-hb and yodyod-hb). That's what my new version has, plus I slightly improved precise placement of the bottom anchors. My version is also in my repo here: https://github.com/markhdavid/heebo-emma-mhd I think if my version is taken.  Hope this can get through now, with my changes. Thanks @emmamarichal and @OdedEzer for patience.

**Comment by emmamarichal** [comment]
Hi @markhdavid, see the last comment: https://forum.glyphsapp.com/t/yiddish-ligatures-should-not-be-considered-ligatures/25468/18

But maybe if I do it by hand it could still work

**Comment by markhdavid** [comment]
> Hi @markhdavid, see the last comment: https://forum.glyphsapp.com/t/yiddish-ligatures-should-not-be-considered-ligatures/25468/18
> 
> But maybe if I do it by hand it could still work

Hi Emma. With my version, you do NOT need to wait for the data to be updated. It works with the old GlyphsLib. My version of the .glyphs source file has those special settings manually set glyph, i.e., properties Category / Subcategory set to Letter / Other in the selection window in Glyphs App. This same workaround was used for Frank Ruhl Libre (already released to Google Fonts) and for David Libre (not yet released, pending other fixes, but these characters are fine in it). So you can be confident it's really not a problem to use this workaround.

**Comment by markhdavid** [comment]
> @markhdavid fonts exported from your file - tell me if it looks okay! If so, @OdedEzer you can merge this PR. I also bumped the version, I made a mistake and put 3.000 whereas the API version is 3.001. Don't know why fontbakery didn't detected it. Since it's a quite big upgrade, I put 3.100.

@emmamarichal Yes, it looks OK -- perfect, actually. Thank you!

**Pull request merged**
